# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nure-proj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nure-proj
	pod 'SnapKit'
	pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'SDWebImage'
  pod 'RealmSwift'
end
